[theme]
background = "default"
primary = "#4285f4" 
secondary = "#1de7ba" 
title = "#f4a64d"
playing = "#f4a64d" 
playing_selected = "#000000" 
playing_bg = "default"
highlight = "#000000" 
highlight_bg = "#e3a16a" 
error = "black"
error_bg = "#8ba8f3"
statusbar = "#191414"
statusbar_progress = "#f4a64d"
statusbar_bg = "#f4a64d"
cmdline = "#4285f4"
cmdline_bg = "#191414"
search_match = "#8ba8f3"
# chatgpt suggested